name: optimize-molecule
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - flask-cors
  - numpy
  - pip
  - python-dotenv
  - stripe
  - pip:
      - pyscf
      - openmm
      - gunicorn
      - flask-sqlalchemy

