name: optimize-molecule
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - flask-cors
  - numpy=1.24.3
  - pip
  - python-dotenv
  - stripe
  - pip:
      - pyscf
      - openmm
      - gunicorn
      - flask-sqlalchemy
      - flask-jwt-extended
      - celery==5.2.7  # Specify version for consistency
      - redis==4.5.4   # Specify version for consistency
      - flower==1.2.0  # Optional: For monitoring tasks