import { 
    COLORS, 
    SHADOWS, 
    FONTS, 
    SPACING, 
    BORDER_RADIUS, 
    TRANSITIONS 
  } from './constants';
  
  // Component style objects with enhanced design
  export const styles = {
    app: {
      minHeight: "100vh",
      padding: SPACING.xl,
      background: `linear-gradient(135deg, ${COLORS.gradientStart} 0%, ${COLORS.gradientEnd} 100%)`,
      color: COLORS.text,
      fontFamily: FONTS.body,
      position: "relative",
      overflow: "hidden",
    },
    container: {
      maxWidth: "1200px",
      margin: "0 auto",
      position: "relative",
      zIndex: 2,
    },
    header: {
      marginBottom: SPACING.xxl,
      textAlign: "center",
      position: "relative",
    },
    headerTitle: {
      fontFamily: FONTS.heading,
      fontSize: "3rem",
      fontWeight: FONTS.weightBold,
      marginBottom: SPACING.md,
      letterSpacing: "-0.025em",
      background: `linear-gradient(to right, ${COLORS.primary}, ${COLORS.secondary}, ${COLORS.tertiary})`,
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      display: "inline-block",
      position: "relative",
    },
    headerSubtitle: {
      fontSize: "1.125rem",
      fontWeight: FONTS.weightLight,
      color: COLORS.textSecondary,
      maxWidth: "700px",
      margin: "0 auto",
    },
    card: {
      backgroundColor: "rgba(30, 41, 59, 0.7)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: BORDER_RADIUS.xl,
      boxShadow: SHADOWS.card,
      padding: SPACING.xl,
      marginBottom: SPACING.xl,
      border: `1px solid ${COLORS.border}`,
      position: "relative",
      overflow: "hidden",
      transition: TRANSITIONS.medium,
    },
    cardWithGlow: {
      backgroundColor: "rgba(30, 41, 59, 0.7)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: BORDER_RADIUS.xl,
      boxShadow: `${SHADOWS.card}, 0 0 20px rgba(56, 189, 248, 0.3)`,
      padding: SPACING.xl,
      marginBottom: SPACING.xl,
      border: `1px solid rgba(56, 189, 248, 0.3)`,
      position: "relative",
      overflow: "hidden",
      transition: TRANSITIONS.medium,
    },
    section: {
      marginBottom: SPACING.xl,
      animation: "fadeIn 0.5s ease-out",
    },
    sectionTitle: {
      fontSize: "1.5rem",
      fontWeight: FONTS.weightSemiBold,
      marginBottom: SPACING.lg,
      color: COLORS.text,
      fontFamily: FONTS.heading,
      position: "relative",
      display: "inline-block",
      paddingBottom: SPACING.xs,
    },
    sectionTitleUnderline: {
      position: "absolute",
      bottom: 0,
      left: 0,
      width: "60px",
      height: "3px",
      background: `linear-gradient(to right, ${COLORS.primary}, ${COLORS.secondary})`,
      borderRadius: BORDER_RADIUS.pill,
    },
    button: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      padding: `${SPACING.sm} ${SPACING.lg}`,
      borderRadius: BORDER_RADIUS.md,
      fontWeight: FONTS.weightMedium,
      fontSize: "0.875rem",
      cursor: "pointer",
      transition: TRANSITIONS.medium,
      boxShadow: SHADOWS.button,
      border: "none",
      outline: "none",
      textDecoration: "none",
      userSelect: "none",
      position: "relative",
      overflow: "hidden",
    },
    primaryButton: {
      background: COLORS.gradientBlue,
      color: COLORS.text,
      "&:hover": {
        transform: "translateY(-2px)",
        boxShadow: SHADOWS.lg,
      },
      "&:active": {
        transform: "translateY(0)",
        boxShadow: SHADOWS.sm,
      },
    },
    successButton: {
      background: COLORS.gradientEmerald,
      color: COLORS.text,
    },
    infoButton: {
      background: COLORS.gradientIndigo,
      color: COLORS.text,
    },
    tabButton: (isActive, color) => ({
      background: isActive 
        ? (color === COLORS.classical 
            ? COLORS.gradientEmerald 
            : COLORS.gradientBlue) 
        : "rgba(30, 41, 59, 0.7)",
      color: COLORS.text,
      padding: `${SPACING.xs} ${SPACING.md}`,
      boxShadow: isActive ? SHADOWS.md : "none",
      fontWeight: isActive ? FONTS.weightSemiBold : FONTS.weightRegular,
      opacity: isActive ? 1 : 0.8,
      borderRadius: BORDER_RADIUS.md,
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
    }),
    fileUpload: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: SPACING.xxl,
      borderRadius: BORDER_RADIUS.xl,
      border: `2px dashed ${COLORS.border}`,
      backgroundColor: "rgba(20, 27, 45, 0.5)",
      cursor: "pointer",
      transition: TRANSITIONS.medium,
      marginBottom: SPACING.xl,
      position: "relative",
      overflow: "hidden",
    },
    fileUploadActive: {
      borderColor: COLORS.primary,
      backgroundColor: `rgba(56, 189, 248, 0.1)`,
    },
    fileUploadIcon: {
      color: COLORS.textSecondary,
      fontSize: "2.5rem",
      marginBottom: SPACING.md,
      transition: TRANSITIONS.medium,
    },
    fileUploadActiveIcon: {
      color: COLORS.primary,
    },
    fileUploadText: {
      fontWeight: FONTS.weightMedium,
      marginBottom: SPACING.xs,
    },
    fileUploadSubtext: {
      fontSize: "0.875rem",
      color: COLORS.textSecondary,
    },
    inputGroup: {
      marginBottom: SPACING.md,
    },
    label: {
      display: "block",
      marginBottom: SPACING.xs,
      fontSize: "0.875rem",
      fontWeight: FONTS.weightMedium,
      color: COLORS.textSecondary,
    },
    input: {
      width: "100%",
      padding: `${SPACING.sm} ${SPACING.md}`,
      backgroundColor: "rgba(15, 23, 42, 0.7)",
      border: `1px solid ${COLORS.border}`,
      borderRadius: BORDER_RADIUS.md,
      color: COLORS.text,
      fontSize: "0.875rem",
      transition: TRANSITIONS.fast,
      "&:focus": {
        borderColor: COLORS.borderHighlight,
        boxShadow: `0 0 0 2px ${COLORS.primary}33`,
        outline: "none",
      },
    },
    parametersContainer: {
      backgroundColor: "rgba(15, 23, 42, 0.7)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: BORDER_RADIUS.xl,
      padding: SPACING.xl,
      marginBottom: SPACING.xl,
      border: `1px solid ${COLORS.border}`,
      boxShadow: SHADOWS.lg,
    },
    parameterGroup: {
      display: "flex",
      alignItems: "center", 
      marginBottom: SPACING.md,
    },
    parameterLabel: {
      flexBasis: "220px",
      flexShrink: 0,
      fontWeight: FONTS.weightMedium,
      color: COLORS.text,
    },
    parameterInput: {
      width: "120px",
      padding: `${SPACING.xs} ${SPACING.sm}`,
      backgroundColor: "rgba(15, 23, 42, 0.8)",
      border: `1px solid ${COLORS.border}`,
      borderRadius: BORDER_RADIUS.md,
      color: COLORS.text,
      fontSize: "0.875rem",
      fontFamily: FONTS.mono,
    },
    parameterSelect: {
      padding: `${SPACING.xs} ${SPACING.md}`,
      backgroundColor: "rgba(15, 23, 42, 0.8)",
      border: `1px solid ${COLORS.border}`,
      borderRadius: BORDER_RADIUS.md,
      color: COLORS.text,
      fontSize: "0.875rem",
      minWidth: "180px",
    },
    warningText: {
      color: COLORS.warning,
      fontSize: "0.75rem",
      marginLeft: SPACING.sm,
      display: "flex",
      alignItems: "center",
      gap: "6px",
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      padding: `${SPACING.xs} ${SPACING.sm}`,
      borderRadius: BORDER_RADIUS.pill,
      fontSize: "0.75rem",
      fontWeight: FONTS.weightSemiBold,
      marginLeft: SPACING.sm,
    },
    warningBadge: {
      backgroundColor: `${COLORS.warning}22`,
      color: COLORS.warning,
      border: `1px solid ${COLORS.warning}44`,
    },
    dangerBadge: {
      backgroundColor: `${COLORS.danger}22`,
      color: COLORS.danger,
      border: `1px solid ${COLORS.danger}44`,
    },
    visualizationContainer: {
      backgroundColor: "rgba(15, 23, 42, 0.7)",
      borderRadius: BORDER_RADIUS.xl,
      overflow: "hidden",
      marginTop: SPACING.xl,
      marginBottom: SPACING.xl,
      boxShadow: SHADOWS.card,
      border: `1px solid ${COLORS.border}`,
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      transition: TRANSITIONS.medium,
    },
    visualizationHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: SPACING.md,
      borderBottom: `1px solid ${COLORS.border}`,
      backgroundColor: "rgba(15, 23, 42, 0.9)",
    },
    visualizationTitle: {
      fontSize: "1.125rem",
      fontWeight: FONTS.weightSemiBold,
      color: COLORS.text,
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    visualizationIcon: {
      color: COLORS.primary,
    },
    visualizationContent: {
      padding: SPACING.md,
    },
    tabs: {
      display: "flex",
      gap: SPACING.xs,
    },
    tab: (isActive, color) => ({
      padding: `${SPACING.sm} ${SPACING.md}`,
      backgroundColor: isActive 
        ? (color === COLORS.classical 
            ? "rgba(16, 185, 129, 0.2)" 
            : "rgba(56, 189, 248, 0.2)")
        : "rgba(15, 23, 42, 0.7)",
      color: isActive 
        ? (color === COLORS.classical 
            ? COLORS.classical 
            : COLORS.quantum)
        : COLORS.textSecondary,
      borderRadius: BORDER_RADIUS.md,
      fontWeight: isActive ? FONTS.weightSemiBold : FONTS.weightRegular,
      cursor: "pointer",
      transition: TRANSITIONS.medium,
      marginRight: SPACING.xs,
      border: `1px solid ${isActive 
        ? (color === COLORS.classical 
            ? "rgba(16, 185, 129, 0.3)" 
            : "rgba(56, 189, 248, 0.3)")
        : "transparent"}`,
      boxShadow: isActive ? SHADOWS.sm : "none",
      display: "flex",
      alignItems: "center",
      gap: "6px",
    }),
    resultsContainer: {
      backgroundColor: "rgba(15, 23, 42, 0.7)",
      borderRadius: BORDER_RADIUS.xl,
      padding: SPACING.xl,
      marginTop: SPACING.xl,
      border: `1px solid ${COLORS.border}`,
      boxShadow: SHADOWS.lg,
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      position: "relative",
      overflow: "hidden",
    },
    resultTitle: {
      fontSize: "1.25rem",
      fontWeight: FONTS.weightSemiBold,
      marginBottom: SPACING.lg,
      paddingBottom: SPACING.sm,
      borderBottom: `1px solid ${COLORS.border}`,
      color: COLORS.text,
      fontFamily: FONTS.heading,
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    resultIcon: {
      color: COLORS.primary,
    },
    resultItem: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: `${SPACING.sm} 0`,
      borderBottom: `1px solid rgba(255, 255, 255, 0.05)`,
    },
    resultLabel: {
      fontWeight: FONTS.weightMedium,
      color: COLORS.textSecondary,
    },
    resultValue: {
      color: COLORS.text,
      fontFamily: FONTS.mono,
      padding: `${SPACING.xs} ${SPACING.sm}`,
      backgroundColor: "rgba(15, 23, 42, 0.5)",
      borderRadius: BORDER_RADIUS.sm,
      fontSize: "0.875rem",
    },
    tooltipContainer: {
      position: "relative",
      display: "inline-block",
    },
    tooltip: {
      position: "absolute",
      bottom: "calc(100% + 10px)",
      left: "50%",
      transform: "translateX(-50%)",
      padding: SPACING.sm,
      backgroundColor: COLORS.cardDark,
      color: COLORS.text,
      borderRadius: BORDER_RADIUS.md,
      fontSize: "0.75rem",
      boxShadow: SHADOWS.md,
      zIndex: 10,
      whiteSpace: "nowrap",
      pointerEvents: "none",
      opacity: 0,
      transition: "opacity 0.2s ease",
      border: `1px solid ${COLORS.border}`,
    },
    tooltipActive: {
      opacity: 1,
    },
    tooltipArrow: {
      position: "absolute",
      top: "100%",
      left: "50%",
      transform: "translateX(-50%)",
      width: 0,
      height: 0,
      borderLeft: "6px solid transparent",
      borderRight: "6px solid transparent",
      borderTop: `6px solid ${COLORS.cardDark}`,
    },
    welcomeMessage: {
      display: "flex",
      alignItems: "center",
      padding: SPACING.lg,
      borderRadius: BORDER_RADIUS.lg,
      border: `1px solid rgba(56, 189, 248, 0.3)`,
      background: "linear-gradient(145deg, rgba(56, 189, 248, 0.1), rgba(37, 99, 235, 0.05))",
      marginBottom: SPACING.xl,
      position: "relative",
      overflow: "hidden",
      boxShadow: `0 8px 16px rgba(0, 0, 0, 0.1), 0 0 0 1px rgba(56, 189, 248, 0.2)`,
    },
    welcomeIcon: {
      color: COLORS.primary,
      fontSize: "1.5rem",
      marginRight: SPACING.md,
      borderRadius: BORDER_RADIUS.circle,
      padding: SPACING.sm,
      backgroundColor: "rgba(56, 189, 248, 0.1)",
      border: `1px solid rgba(56, 189, 248, 0.2)`,
    },
    buttonGroup: {
      display: "flex",
      gap: SPACING.sm,
      marginTop: SPACING.lg,
    },
    buttonGroupItem: {
      flex: 1,
    },
    subscriptionNotice: {
      background: "linear-gradient(145deg, rgba(251, 191, 36, 0.1), rgba(245, 158, 11, 0.05))",
      border: `1px solid rgba(251, 191, 36, 0.3)`,
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.lg,
      marginBottom: SPACING.lg,
      display: "flex",
      alignItems: "center",
      boxShadow: `0 4px 6px rgba(0, 0, 0, 0.1)`,
    },
    subscriptionNoticeIcon: {
      color: COLORS.warning,
      marginRight: SPACING.md,
      fontSize: "1.25rem",
      backgroundColor: "rgba(251, 191, 36, 0.1)",
      padding: SPACING.xs,
      borderRadius: BORDER_RADIUS.circle,
    },
    viewerContainer: {
      border: `1px solid ${COLORS.border}`,
      borderRadius: BORDER_RADIUS.lg,
      overflow: "hidden",
      height: "450px",
      backgroundColor: "rgba(15, 23, 42, 0.5)",
      boxShadow: `inset 0 0 20px rgba(0, 0, 0, 0.2)`,
    },
    optimizeButtonContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      marginTop: SPACING.xl,
    },
    optimizeButton: (type, isLoading) => ({
      padding: `${SPACING.md} ${SPACING.xxl}`,
      background: isLoading 
        ? "linear-gradient(145deg, #475569, #334155)" 
        : (type === "classical" 
            ? COLORS.gradientEmerald 
            : COLORS.gradientBlue),
      color: COLORS.text,
      borderRadius: BORDER_RADIUS.lg,
      fontWeight: FONTS.weightSemiBold,
      cursor: isLoading ? "not-allowed" : "pointer",
      opacity: isLoading ? 0.7 : 1,
      transition: TRANSITIONS.bounce,
      border: "none",
      boxShadow: isLoading ? SHADOWS.sm : SHADOWS.lg,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      minWidth: "260px",
      position: "relative",
      overflow: "hidden",
      fontSize: "1rem",
      letterSpacing: "0.5px",
    }),
    optimizeButtonShine: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      background: "linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent)",
      transform: "translateX(-100%)",
      animation: "shimmer 2s infinite",
      pointerEvents: "none",
    },
    freeUserNotice: {
      fontSize: "0.75rem",
      color: COLORS.textSecondary,
      marginTop: SPACING.sm,
      textAlign: "center",
      maxWidth: "400px",
    },
    spinner: {
      width: "18px",
      height: "18px",
      border: `2px solid rgba(255, 255, 255, 0.3)`,
      borderTopColor: COLORS.text,
      borderRadius: "50%",
      animation: "spin 1s linear infinite",
      marginRight: SPACING.sm,
    },
    howToUseButton: {
      position: "absolute",
      top: SPACING.md,
      left: SPACING.md,
      padding: `${SPACING.xs} ${SPACING.sm}`,
      background: "linear-gradient(145deg, rgba(16, 185, 129, 0.9), rgba(5, 150, 105, 0.9))",
      color: "white",
      borderRadius: BORDER_RADIUS.md,
      fontSize: "0.75rem",
      fontWeight: FONTS.weightSemiBold,
      cursor: "pointer",
      zIndex: 5,
      display: "flex",
      alignItems: "center",
      boxShadow: SHADOWS.lg,
      border: "1px solid rgba(16, 185, 129, 0.3)",
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
    },
    howToUseIcon: {
      marginRight: SPACING.xs,
    },
    cancelSubscriptionButton: {
      position: "absolute",
      top: SPACING.md,
      right: SPACING.md,
      padding: `${SPACING.xs} ${SPACING.sm}`,
      background: "linear-gradient(145deg, rgba(244, 63, 94, 0.9), rgba(225, 29, 72, 0.9))",
      color: "white",
      borderRadius: BORDER_RADIUS.md,
      fontSize: "0.75rem",
      fontWeight: FONTS.weightMedium,
      cursor: "pointer",
      zIndex: 5,
      display: "flex",
      alignItems: "center",
      boxShadow: SHADOWS.lg,
      border: "1px solid rgba(244, 63, 94, 0.3)",
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
    },
    cancelSubscriptionIcon: {
      marginRight: SPACING.xs,
    },
    popup: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      backdropFilter: "blur(10px)",
      WebkitBackdropFilter: "blur(10px)",
      zIndex: 1000,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    popupContent: {
      backgroundColor: "rgba(15, 23, 42, 0.95)",
      borderRadius: BORDER_RADIUS.xxl,
      boxShadow: SHADOWS.popup,
      width: "80%",
      height: "80%",
      maxWidth: "1200px",
      padding: SPACING.xxl,
      position: "relative",
      overflow: "hidden",
      border: `1px solid ${COLORS.border}`,
      backdropFilter: "blur(16px)",
      WebkitBackdropFilter: "blur(16px)",
    },
    popupClose: {
      position: "absolute",
      top: SPACING.md,
      right: SPACING.md,
      width: "36px",
      height: "36px",
      borderRadius: BORDER_RADIUS.circle,
      background: "linear-gradient(145deg, rgba(244, 63, 94, 0.9), rgba(225, 29, 72, 0.9))",
      color: "white",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      zIndex: 1,
      border: "none",
      boxShadow: SHADOWS.md,
    },
    popupScroll: {
      height: "calc(100% - 20px)",
      overflowY: "auto",
      padding: `${SPACING.md} 0`,
    },
    decorativeBg: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: `
        radial-gradient(circle at 10% 10%, rgba(56, 189, 248, 0.08), transparent 40%),
        radial-gradient(circle at 90% 90%, rgba(16, 185, 129, 0.08), transparent 40%),
        radial-gradient(circle at 90% 10%, rgba(168, 85, 247, 0.08), transparent 30%),
        radial-gradient(circle at 10% 90%, rgba(236, 72, 153, 0.08), transparent 30%)
      `,
      zIndex: 1,
      pointerEvents: "none",
    },
    decorativeLine: {
      position: "absolute",
      height: "1px",
      width: "100%",
      background: "linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.2), transparent)",
      zIndex: 1,
      pointerEvents: "none",
    },
    methodSelectionContainer: {
      display: "flex",
      justifyContent: "center",
      gap: SPACING.lg,
      marginBottom: SPACING.xl,
    },
    methodSelectionButton: (isActive, type) => ({
      flex: 1,
      maxWidth: "280px",
      padding: SPACING.xl,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(15, 23, 42, 0.7)",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: BORDER_RADIUS.xl,
      cursor: "pointer",
      transition: TRANSITIONS.bounce,
      border: `2px solid ${isActive 
        ? (type === "classical" 
            ? COLORS.classical 
            : COLORS.quantum) 
        : "transparent"}`,
      boxShadow: isActive ? SHADOWS.lg : SHADOWS.md,
      position: "relative",
      overflow: "hidden",
    }),
    methodIcon: {
      fontSize: "2.5rem",
      marginBottom: SPACING.md,
      color: COLORS.text,
      padding: SPACING.sm,
      borderRadius: BORDER_RADIUS.circle,
      backgroundColor: isActive => isActive 
        ? (type => type === "classical" 
            ? "rgba(16, 185, 129, 0.1)" 
            : "rgba(56, 189, 248, 0.1)")(type) 
        : "rgba(30, 41, 59, 0.5)",
      border: `1px solid ${isActive => isActive 
        ? (type => type === "classical" 
            ? "rgba(16, 185, 129, 0.3)" 
            : "rgba(56, 189, 248, 0.3)")(type) 
        : "transparent"}`,
    },
    methodTitle: {
      fontWeight: FONTS.weightSemiBold,
      marginBottom: SPACING.xs,
      color: COLORS.text,
      fontSize: "1.125rem",
    },
    methodDescription: {
      fontSize: "0.875rem",
      color: COLORS.textSecondary,
      textAlign: "center",
      lineHeight: 1.5,
    },
    fadeIn: {
      animation: "fadeIn 0.5s ease-in-out",
    },
    contentWrapper: {
      animation: "fadeIn 0.5s ease-in-out",
    },
    glowEffect: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: `radial-gradient(circle at 50% 50%, ${COLORS.primary}22, transparent 70%)`,
      opacity: 0,
      transition: "opacity 0.5s ease",
      "&:hover": {
        opacity: 1,
      },
    },
  };